# NOTE: Before running docker-compose, ensure this file is located in the project root directory (one level above SkillVault/)
# NOTE: The build context is '.', so the Dockerfile path must be relative to the root directory, e.g., Docker/backend/Dockerfile-example
# NOTE: Your project structure should resemble:
#       rootDir/
#         ├── docker-compose.yml
#         ├── Docker/backend/Dockerfile-example
#         └── SkillVault/ (your source code and Maven project files)

services:
  mysql:
    image: mysql:8.0
    container_name: skillvault_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE-ME
      MYSQL_DATABASE: skillvault_db
      MYSQL_USER: CHANGE-ME
      MYSQL_PASSWORD: CHANGE-ME
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile-example
    depends_on:
      - mysql
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/skillvault_db
      SPRING_DATASOURCE_USERNAME: CHANGE-ME
      SPRING_DATASOURCE_PASSWORD: CHANGE-ME
    entrypoint: ["java", "-jar", "app.jar"]

volumes:
  mysqldata:
